version: '3'

services:
  # -------------- MySql
  mysql:
    image: mimysql:5.6
    container_name: book-mysql
    environment:
      MYSQL_DATABASE: dbmedia
      MYSQL_USER: usermedia
      MYSQL_PASSWORD: paso
      MYSQL_ROOT_PASSWORD: paso
      MYSQL_ROOT_HOST: '127.0.0.1'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    
  web:
   # -------------- Apache + PHP
    image: miphp:7.4
    container_name: book-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
      