## Descargamos una versión concreta de Apache
FROM httpd:2.4
## Creamos un fichero index.html en el directorio por defecto de httpd
RUN echo "Mi primer Dockerfile. Hola Mundo!" > /usr/local/apache2/htdocs/index.html
## Exponemos el Puerto 80
EXPOSE 80